# -*- coding: utf-8 -*-
"""DataAnalysis_Amir.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jMSuMO9e10BwSvixq_Egk-OZBTuF0fdJ

**This is a notebook that will allow you to analyze your data. The first thing you will want to do is make a copy of this file with your own name (e.g. DataAnalysis_Garcia.ipynb). Otherwise we'll all be editing the same file and it will get very complicated and confusing!**

Each section or "cell" has to be run (or "executed"), starting with the first cell.

You can execute a cell by pressing the "play arrow" in the top left of the cell or by putting the cursor into the cell, clicking on it (as if to edit it) and then hitting shift-enter.

The first cell will require some interaction as it gets permission to access the google drive.
"""

# this is stuff that sets up your environment and gets the program ready
# you only need to run this "cell" once each time you come back to this analysis

# mount the gdrive directories
# this allows the code to access the google drive on which the data files are located

from google.colab import drive
drive.mount('/content/gdrive')

# this tells the python code which libraries of code to load (so we don't have to code *everything* from scratch!)

from matplotlib import pyplot as plt
import numpy as np

# this is the Gdrive folder in which the data is located
infolder='gdrive/'

# run this every time you change the filename or at the beginning of your analysis session

# this is the name of the file you want to analyze
 
filename="data.CSV"

# This reads the data file into some array variables so that we can plot them later

file1 = open(infolder+filename,"r")
file1.readline()    # read the headers

i=0
Time=[]
SQM=[]
Red=[]
Green=[]
Blue=[]
CT=[]
Lux=[]
r=[]
g=[]
b=[]
c=[]
for line in file1:
    ld=line.split(",")
    if len(ld)==11: 
        Time.append(int(ld[0]))
        SQM.append(float(ld[1]))
        Red.append(float(ld[2]))
        Green.append(float(ld[3]))
        Blue.append(float(ld[4]))
        CT.append(int(ld[5]))
        Lux.append(int(ld[6]))
        r.append(int(ld[7]))
        g.append(int(ld[8]))
        b.append(int(ld[9]))
        c.append(int(ld[10]))

#    print(i,ld)
#    if i>100:
#        break
#    i=i+1

Time=np.array(Time)
SQM=np.array(SQM)
Red=np.array(Red)
Green=np.array(Green)
Blue=np.array(Blue)
CT=np.array(CT)
Lux=np.array(Lux)
r=np.array(r)
g=np.array(g)
b=np.array(b)
c=np.array(c)

file1.close()

print("Number of lines in data file:", len(Time))

# And finally, here we plot some of the data. This is where you can have fun lokoing at your data!
# try changing what you plot against what, and adjust the limits ("plt.xlim" etc.)

plt.figure(figsize=(15,10))
plt.xticks(fontsize=18)     # this just changes the font sizes
plt.yticks(fontsize=18)

#plt.xlim(0,800)      # show only the x range between 0 and 25,000
#plt.ylim(0,100)        # show only the y range between 0 and 500

plt.xlabel('Time (sec)', size = 20)
plt.ylabel('Intensity [mW/m2 (SQM), lux(r,g,b,c)]', size = 20)
# the /1000 turns the milliseconds into seconds
plt.scatter(Time/1000,r,s=0.3,color='red', label = "Red Channel (lux)")   
plt.scatter(Time/1000,g,s=0.3,color='green', label = "Green Channel (lux)")
plt.scatter(Time/1000,b,s=0.3,color='blue', label = "Blue Channel (lux)") 
plt.scatter(Time/1000,c,s=0.3,color='grey', label = "Clear Channel (lux)") 
plt.scatter(Time/1000,SQM,s=0.3,color='black', label = "SQM (mW/m2)")
plt.legend(loc="upper right", prop={"size":20}, markerscale=20)
plt.show()

"""/end"""